version: "3"

services:
  redis:
    image: 'redis:5.0.3-alpine'
    command: redis-server
    volumes:
      - 'redis:/data'
    networks: 
      - general

  celery:
    build: ./serverPy
    command: "celery -A app.celery worker -l INFO"
    networks: 
      - general

  gunicorn:
    build: ./serverPy
    command: "gunicorn -w 4 -b 0.0.0.0:5000 app:app"
    ports:
      - "5000:5000"
    networks: 
      - general

  serverdb:
    build: ./serverDB
    environment:
      port: "3031"
      dbPort: "27017"
      hostName: "mongo"
    networks:
      - general
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    networks:
      - general
    volumes:
      - mongoData:/data/db
  
  serverauth:
    build: ./serverAuth
    ports:
      - "3030:3030"
    networks:
      - general
    environment:
      DB_SERVICE_NAME: "serverdb"

volumes:
  redis:
  mongoData:

networks:
  general: