version: "3"

services:
  gunicorn:
    build:
      context: ./serverPyV2/api
      dockerfile: Dockerfile
    restart: always
    ports:
     - "5001:5001"
    networks: 
      - general
    depends_on:
      - redis
  celery:
    build:
      context: ./serverPyV2/celery-queue
      dockerfile: Dockerfile
    depends_on:
      - redis
    networks: 
      - general
  redis:
    image: redis
    networks:
      - general

  serverdb:
    build: ./serverDB
    environment:
      port: "3031"
      dbPort: "27017"
      hostName: "mongo"
    networks:
      - general
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    networks:
      - general
    volumes:
      - mongoData:/data/db
  
  serverauth:
    build: ./serverAuth
    ports:
      - "3030:3030"
    networks:
      - general
    environment:
      DB_SERVICE_NAME: "serverdb"
      DB_SERVICE_PORT: "3031"
    env_file:
    - secret.env

volumes:
  mongoData:

networks:
  general: